let app = Vue.createApp({
    data(){
        return{
            title: [
                {image: '../image/locandine/locandina (1).jpg',
                    riferimento: 'sch-film1',
                    trailer: "https://www.youtube.com/embed/eHp3MbsCbMg",
                    text: 'UNCHARTED', 
                    Regista: "Ruben Fleischer",
                    Genere: "Azione, Avventura",
                    Anno: "2022",
                    Paese: "USA",
                    Durata: "116 min",
                    Data: "17 febbraio 2022",
                    Distribuzione: "Sony Pictures/ Warner Bros. Italia",
                    trama:"Basato su una delle serie di videogiochi più vendute e acclamate dalla critica, Uncharted presenta al pubblico il giovane e furbo Nathan Drake (Tom Holland)nella sua prima avventura alla ricerca del tesoro con l’arguto partner Victor “Sully” Sullivan (Mark Wahlberg). In un’epica avventura piena di azione che attraversa il mondo intero, i due protagonisti partono alla pericolosa ricerca del “più grande tesoro mai trovato”, inseguendo indizi che potrebbero condurli al fratello di Nathan, scomparso da tempo."},
                {image: "../image/locandine/locandina (2).jpg",
                    riferimento: 'sch-film2',
                    trailer: "https://www.youtube.com/embed/ALtLuqMUOI4",
                    text: 'LA FIGLIA OSCURA',
                    Regista: "Maggie Gyllenhaal",
                    Genere: "Drammatico",
                    Anno: "2021",
                    Paese: "USA, Gran Bretagna, Israele, Grecia",
                    Durata: "121 min",
                    Data: "07 aprile 2022",
                    Distribuzione: "BIM Distribuzione",
                    trama: "Durante una vacanza al mare da sola, Leda (Olivia Colman) rimane incuriosita e affascinata da una giovane madre (Dakota Johnson) e dalla sua figlioletta mentre le osserva sulla spiaggia. Turbata dal loro irresistibile rapporto, (e dalla loro chiassosa e minacciosa famiglia allargata), Leda è sopraffatta dai suoi stessi ricordi personali dei sentimenti di terrore, confusione e intensità provati nelle prime fasi della maternità. Un gesto impulsivo sconvolge Leda e la proietta nello strano e sinistro mondo della sua stessa mente, dove è costretta ad affrontare le scelte non convenzionali che ha compiuto quando era una giovane madre e le loro conseguenze."},
                {image: "../image/locandine/locandina (3).jpg",
                    trailer: "https://www.youtube.com/embed/TXBPBQJMTNA",
                    text: 'GLI IDOLI DELLE DONNE',
                    Regista: "Lillo, Greg, Eros Puglielli",
                    Genere: "Commedia",
                    Anno: "2022",
                    Paese: "Italia",
                    Durata: "91 min",
                    Data: "14 aprile 2022",
                    Distribuzione: "Vision Distribution",
                    trama: "Filippo, uno dei gigolò più desiderati, in seguito a un incidente subisce un intervento al volto che ne cambia completamente la fisionomia. Non riuscendo più ad avere successo nel suo lavoro, decide di chiedere aiuto a Max, uno dei più grandi gigolò esistenti. L'intervento di Max però non riesce a sortire l'effetto sperato, finché Filippo non incontra Juanita, una colombiana che si innamora di lui e si scoprirà essere figlia di due trafficanti di droga."},
                {image: "../image/locandine/locandina (4).jpg",
                    trailer: "https://www.youtube.com/embed/0x5z7bzO2HQ",
                    text: 'IL SESSO DEGLI ANGELI',
                    Regista: "Leonardo Pieraccioni",
                    Genere: "Commedia",
                    Anno: "2022",
                    Paese: "Italia",
                    Durata: "91 min",
                    Data: "21 aprile 2022",
                    Distribuzione: "01 Distribution",
                    trama: "Don Simone (Leonardo Pieraccioni) è un prete di frontiera con una chiesetta sempre in difficoltà e mai frequentata dai ragazzi che preferiscono, piuttosto, lo “stare insieme” dei social. Finalmente Don Simone riceve una fantastica notizia: un eccentrico zio gli ha lasciato in eredità un’avviatissima attività in Svizzera che potrà risollevare le sorti economiche del suo oratorio sempre deserto! Ma arrivato a Lugano il nostro prete scopre di aver ereditato… un bordello!"},
                {image: "../image/locandine/locandina (5).jpg",
                    trailer: "https://www.youtube.com/embed/vscYM0_VYd0",
                    text: 'LA CENA PERFETTA',
                    Regista: "Davide Minnella",
                    Genere: "Commedia",
                    Anno: "2022",
                    Paese: "Italia",
                    Durata: "106 min",
                    Data: "26 aprile 2022",
                    Distribuzione: "Vision Distribution",
                    trama: "Carmine, un camorrista dal cuore buono, gestisce un ristorante per riciclare soldi sporchi, e si ritrova a collaborare con Consuelo, una chef alla ricerca della perfezione. L’amore per il cibo e il sogno di conquistare una stella Michelin daranno ad entrambi una seconda possibilità e un’occasione di riscatto."},
                {image: "../image/locandine/locandina (6).jpg",
                    trailer: "https://www.youtube.com/embed/-BgszFX8fxk",
                    text: 'SULLE NUVOLE',
                    Regista: "Tommaso Paradiso",
                    Genere: "Sentimentale",
                    Anno: "2022",
                    Paese: "Italia",
                    Durata: "101 min",
                    Data: "26 aprile 2022",
                    Distribuzione: "Warner Bros. Entertainment Italia",
                    trama: "Nic Vega (Marco Cocci) ha un passato di successo nella musica, con alle spalle una gloriosa carriera da cantante e una grande storia d’amore chiusa da anni. Ormai in crisi da tempo, quando realizza di aver perso tutto – fama, amici e ispirazione – Nic decide di tornare da lei, Francesca (Barbara Ronchi), irrompendo così nella sua vita serena e felice. Potranno i ricordi riaccendere l’amore e la passione di una volta?"},
                {image: "../image/locandine/locandina (7).jpg",
                    trailer: "https://www.youtube.com/embed/Cs05cxkL13c",
                    text: "AMMA'S WAY",
                    Regista: "Anna Agnelli",
                    Genere: "Documentario",
                    Anno: "2022",
                    Paese: "Italia",
                    Durata: "87 min",
                    Data: "02 maggio 2022",
                    Distribuzione: "Nexo Digital",
                    trama: "La determinazione, le emozioni e la gioia di una donna visionaria e travolgente, un personaggio globale che non si stanca di combattere per la pace e che, partendo dalla sua India, ha raccolto sostenitori e volontari in tutto il mondo. In un periodo come quello che stiamo attraversando, dove il contatto fisico è stato messo a dura prova dalla pandemia, l'abbraccio di Amma assume una forza ancora più sconvolgente."},
                {image: "../image/locandine/locandina (8).jpg",
                    trailer: "https://www.youtube.com/embed/18rC8KIETXI",
                    text: "L'ARMA DELL'INGANNO",
                    Regista: "John Madden",
                    Genere: "Drammatico, Guerra",
                    Anno: "2022",
                    Paese: "USA",
                    Durata: "128 min",
                    Data: "12 maggio 2022",
                    Distribuzione: "Warner Bros. Italia",
                    trama: "Gli Alleati sono pronti a sbarcare in Europa, precisamente in Sicilia, per combattere l'armata tedesca, ma si trovano di fronte un arduo compito: proteggere le loro forze dal fuoco nazista ed evitare così quello che sarebbe un massacro certo."},
                {image: "../image/locandine/locandina (9).jpg",
                    trailer: "https://www.youtube.com/embed/23gp-Sf1Oo8",
                    text: 'TWENTY ONE PILOTS',
                    Regista: "Jason Zada",
                    Genere: "Documentario, Musicale",
                    Anno: "2021",
                    Paese: "USA",
                    Durata: "105 min",
                    Data: "19 maggio 2022",
                    Distribuzione: "Nexo Digital",
                    trama: "Il film offre una reinvenzione psichedelica e teatrale delle performance live della band Twenty One Pilots. Questo concerto intenso e abbagliante immerge lo spettatore nelle dinamiche e nel catalogo eclettico di una delle band più creative dell’attuale panorama musicale mondiale."},
                {image: "../image/locandine/locandina (10).jpg",
                    trailer: "https://www.youtube.com/embed/afbWges06hA",
                    text: 'SPENCER',
                    Regista: "Pablo Larraín",
                    Genere: "Drammatico, Biografico",
                    Anno: "2021",
                    Paese: "USA",
                    Durata: "117 min",
                    Data: "24 marzo 2022",
                    Distribuzione: "01 Distribution, Leone Film Group",
                    trama: "Nel 1991, durante le vacanze di Natale con la famiglia reale a Sandringham House, nel Norfolk, Diana Spencer decide di porre fine al suo matrimonio da tempo in crisi con Carlo, principe del Galles."},
                {image: "../image/locandine/locandina (11).jpg",
                    trailer: "https://www.youtube.com/embed/i0in1cRXgE8",
                    text: 'I SEGRETI DI SILENTE',
                    Regista: "David Yates",
                    Genere: "Avventura, Family, Fantasy",
                    Anno: "2022",
                    Paese: "USA",
                    Durata: "142 min",
                    Data: "13 aprile 2022",
                    Distribuzione: "Warner Bros. Pictures",
                    trama: "Il professor Albus Silente sa che il potente mago oscuro Gellert Grindelwald si sta muovendo per prendere il controllo del mondo magico. Incapace di fermarlo da solo, incarica il magizoologo Newt Scamander di guidare un'intrepida squadra di maghi, streghe e un coraggioso fornaio Babbano in una pericolosa missione. Durante il loro percorso incontreranno animali vecchi e nuovi e si scontreranno con la legione di seguaci di Grindelwald, in costante crescita. Ma con la posta in gioco così alta, per quanto tempo Silente potrà restare in disparte?"},
                {image: "../image/locandine/locandina (12).jpg",
                    trailer: "https://www.youtube.com/embed/OwbMHEuPEJo",
                    text: 'THE LOST CITY',
                    Regista: "Aaron Nee, Adam Nee",
                    Genere: "Azione, Avventura, Commedia",
                    Anno: "2022",
                    Paese: "USA",
                    Durata: "112 min",
                    Data: "21 aprile 2022",
                    Distribuzione: "Eagle Pictures",
                    trama: "Volendo dimostrare che può essere un eroe nella vita reale e non solo sulle pagine dei suoi libri, Alan parte per salvarla. Spinta in un'epica avventura nella giungla, l'improbabile coppia dovrà lavorare insieme per sopravvivere agli elementi e trovare l'antico tesoro prima che sia perso per sempre."},
                {image: "../image/locandine/locandina (13).jpg",
                    trailer: "https://www.youtube.com/embed/BZnKiAeg9_8",
                    text: 'UNA VITA IN FUGA',
                    Regista: "Sean Penn",
                    Genere: "Thriller, Drammatico",
                    Anno: "2021",
                    Paese: "USA",
                    Durata: "107 min",
                    Data: "31 marzo 2022",
                    Distribuzione: "Lucky Red",
                    trama: "Narra il rapporto irrisolto tra un padre bugiardo e criminale e una figlia che, invece, ha proprio il mito di papà. Almeno fino all'età adulta… Dalla storia incredibilmente vera del truffatore John Bryson Vogel, l'amore e odio della figlia Jessica per il genitore."},
                {image: "../image/locandine/locandina (14).jpg",
                    trailer: "https://www.youtube.com/embed/PFPTcbqWoc8",
                    text: 'THIS MUCH I KNOW TO BE TRUE',
                    Regista: "Andrew Dominik",
                    Genere: "Documentario",
                    Anno: "2022",
                    Paese: "Gran Bretagna",
                    Durata: "101 min",
                    Data: "23 maggio 2022",
                    Distribuzione: "Nexo Digital",
                    trama: 'Focus sulla relazione creativa e sulle canzoni dei due ultimi album in studio di Nick Cave e Warren Ellis, "Ghosteen" e "Carnage".'},
                {image: "../image/locandine/locandina (15).jpg",
                    trailer: "https://www.youtube.com/embed/95j_EVjYI_M",
                    text: 'TOP GUN',
                    Regista: "Joseph Kosinski",
                    Genere: "Azione",
                    Anno: "2022",
                    Paese: "USA",
                    Durata: "131 min",
                    Data: "25 maggio 2022",
                    Distribuzione: "Eagle Pictures / Paramount Pictures Italia",
                    trama: "Un pilota di caccia si innamora della propria bionda istruttrice, Charlotte Blackwood, e si crede responsabile della morte del copilota. L'esperienza nel programma di formazione lo forza a crescere."},
                {image: "../image/locandine/locandina (16).jpg",
                    trailer: "https://www.youtube.com/embed/EyGEX74LjVo",
                    text: 'SING',
                    Regista: "Garth Jennings",
                    Genere: "Animazione, Commedia, Musicale",
                    Anno: "2016",
                    Paese: "USA",
                    Durata: "110 min",
                    Data: "04 gennaio 2017",
                    Distribuzione: "Universal Pictures",
                    trama: "Buster, un koala proprietario di un teatro ormai caduto in disgrazia, vuole raggiungere il successo partecipando a un'importante competizione canora, ma per vincere deve affrontare cinque accaniti concorrenti."},
                {image: "../image/locandine/locandina (17).jpg",
                    trailer: "https://www.youtube.com/embed/ow-L4bFkEV4",
                    text: 'THE  NORTHMAN',
                    Regista: "Robert Eggers",
                    Genere: "Avventura, Drammatico",
                    Anno: "2022",
                    Paese: "USA, Gran Bretagna",
                    Durata: "140 min",
                    Data: "21 aprile 2022",
                    Distribuzione: "Universal Pictures",
                    trama: "Il principe Amleth sta per diventare un uomo quando suo padre viene brutalmente assassinato. Due decenni dopo, Amleth, ora un vichingo, incontra una veggente che gli ricorda il suo voto."},
                {image: "../image/locandine/locandina (18).jpg",
                    trailer: "https://www.youtube.com/embed/SHrj60ux5AE",
                    text: 'CORRO DA TE',
                    Regista: "Riccardo Milani",
                    Genere: "Commedia, Sentimentale",
                    Anno: "2022",
                    Paese: "Italia",
                    Durata: "113 min",
                    Data: "17 marzo 2022",
                    Distribuzione: "Vision Distribution, Universal Pictures",
                    trama: "Gianni (interpretato da Pierfrancesco Favino) è un aitante scapolo di 50 anni a cui la vita ha dato tutto, o così sembra: è un uomo sportivo e di successo, è proprietario di un brand di scarpe noto in tutto il mondo ed è in grado di conquistare qualsiasi donna lui desideri."}]
        }
    }
})

app.mount("#app")