insert into film values ('Uncharted', 'Ruben Fleischer', 'Azione, Avventura', '2022', 'USA', '116 min', '17 febbraio 2022', 'Sony Pictures/ Warner Bros. Italia', 'Basato su una delle serie di videogiochi più vendute e acclamate dalla critica, Uncharted presenta al pubblico il giovane e furbo Nathan Drake (Tom Holland)nella sua prima avventura alla ricerca del tesoro con l’arguto partner Victor “Sully” Sullivan (Mark Wahlberg). In un’epica avventura piena di azione che attraversa il mondo intero, i due protagonisti partono alla pericolosa ricerca del “più grande tesoro mai trovato”, inseguendo indizi che potrebbero condurli al fratello di Nathan, scomparso da tempo.', '../image/locandine/locandina (1).jpg', 'https://www.youtube.com/embed/eHp3MbsCbMg', 'sanlorenzo-cerveteri-latina');

insert into film values ('La figlia oscura', 'Maggie Gyllenhaal', 'Drammatico', '2021', 'USA, Gran Bretagna, Israele, Grecia', '121 min', '07 aprile 2022', 'BIM Distribuzione', 'Durante una vacanza al mare da sola, Leda (Olivia Colman) rimane incuriosita e affascinata da una giovane madre (Dakota Johnson) e dalla sua figlioletta mentre le osserva sulla spiaggia. Turbata dal loro irresistibile rapporto, (e dalla loro chiassosa e minacciosa famiglia allargata), Leda è sopraffatta dai suoi stessi ricordi personali dei sentimenti di terrore, confusione e intensità provati nelle prime fasi della maternità. Un gesto impulsivo sconvolge Leda e la proietta nello strano e sinistro mondo della sua stessa mente, dove è costretta ad affrontare le scelte non convenzionali che ha compiuto quando era una giovane madre e le loro conseguenze.', '../image/locandine/locandina (2).jpg', 'https://www.youtube.com/embed/ALtLuqMUOI4', 'latina');

insert into film values ('Gli idoli delle donne', 'Lillo, Greg, Eros Puglielli', 'Commedia', '2022', 'Italia', '91 min', '14 aprile 2022', 'Vision Distribution', 'Filippo, uno dei gigolò più desiderati, in seguito a un incidente subisce un intervento al volto che ne cambia completamente la fisionomia. Non riuscendo più ad avere successo nel suo lavoro, decide di chiedere aiuto a Max, uno dei più grandi gigolò esistenti. L intervento di Max però non riesce a sortire l effetto sperato, finché Filippo non incontra Juanita, una colombiana che si innamora di lui e si scoprirà essere figlia di due trafficanti di droga.', '../image/locandine/locandina (3).jpg', 'https://www.youtube.com/embed/TXBPBQJMTNA', 'cerveteri');

insert into film values ('Il sesso degli angeli', 'Leonardo Pieraccioni', 'Commedia', '2022', 'Italia', '91 min', '21 aprile 2022', '01 Distribution', 'Don Simone (Leonardo Pieraccioni) è un prete di frontiera con una chiesetta sempre in difficoltà e mai frequentata dai ragazzi che preferiscono, piuttosto, lo “stare insieme” dei social. Finalmente Don Simone riceve una fantastica notizia: un eccentrico zio gli ha lasciato in eredità un’avviatissima attività in Svizzera che potrà risollevare le sorti economiche del suo oratorio sempre deserto! Ma arrivato a Lugano il nostro prete scopre di aver ereditato… un bordello!', '../image/locandine/locandina (4).jpg', 'https://www.youtube.com/embed/0x5z7bzO2HQ', 'sanlorenzo-cerveteri');

insert into film values ('La cena perfetta', 'Davide Minnella', 'Commedia', '2022', 'Italia', '106 min', '26 aprile 2022', 'Vision Distribution', 'Carmine, un camorrista dal cuore buono, gestisce un ristorante per riciclare soldi sporchi, e si ritrova a collaborare con Consuelo, una chef alla ricerca della perfezione. L’amore per il cibo e il sogno di conquistare una stella Michelin daranno ad entrambi una seconda possibilità e un’occasione di riscatto.', '../image/locandine/locandina (5).jpg', 'https://www.youtube.com/embed/vscYM0_VYd0', 'sanlorenzo-latina');

insert into film values ('Sulle nuvole', 'Tommaso Paradiso', 'Sentimentale', '2022', 'Italia', '101 min', '26 aprile 2022', 'Warner Bros. Entertainment Italia', 'Nic Vega (Marco Cocci) ha un passato di successo nella musica, con alle spalle una gloriosa carriera da cantante e una grande storia d’amore chiusa da anni. Ormai in crisi da tempo, quando realizza di aver perso tutto – fama, amici e ispirazione – Nic decide di tornare da lei, Francesca (Barbara Ronchi), irrompendo così nella sua vita serena e felice. Potranno i ricordi riaccendere l’amore e la passione di una volta?', '../image/locandine/locandina (6).jpg', 'https://www.youtube.com/embed/-BgszFX8fxk', 'latina');

insert into film values ('Morbius', 'Daniel Espinosa', 'Fantasy, Azione, Dramma', '2022', 'USA', '108 min', '31 marzo 2022', 'Sony Pictures/ Warner Bros.', 'L’attore Premio Oscar Jared Leto presta il volto al più tormentato antieroe dell’universo Marvel. Il Dr. Morbius è un biologo geniale, tormentato da una rara malattia del sangue. Determinato a trovare una cura, tenta una mossa disperata.', '../image/locandine/locandina (7).jpg', 'https://www.youtube.com/embed/6FxUdXgEeVQ', 'cerveteri');

insert into film values ('Troppo Cattivi', 'Pierre Perifel', 'Animazione', '2022', 'USA', '100 min', '31 marzo 2022', 'Sony Pictures/ Warner Bros.', 'Dal 31 marzo arrivano al cinema i Troppo Cattivi. Mister Wolf, Mister Snake, Mister Shark, Mister Piranha e Miss Tarantula formano la banda di criminali più ricercata della storia. Dopo anni di rapine vengono finalmente catturati, e Mister Wolf decide di fare un patto (che non ha intenzione di mantenere) per evitare la prigione: i Troppo Cattivi diventeranno buoni.', '../image/locandine/locandina (8).jpg', 'https://www.youtube.com/embed/9IV992L5bDw', 'sanlorenzo-cerveteri-latina');

insert into film values ('Twenty one pilots', 'Jason Zada', 'Documentario, musicale', '2021', 'USA', '105 min', '19 maggio 2022', 'Nexo Digital', 'Il film offre una reinvenzione psichedelica e teatrale delle performance live della band Twenty One Pilots. Questo concerto intenso e abbagliante immerge lo spettatore nelle dinamiche e nel catalogo eclettico di una delle band più creative dell’attuale panorama musicale mondiale.', '../image/locandine/locandina (9).jpg', 'https://www.youtube.com/embed/23gp-Sf1Oo8', 'sanlorenzo-cerveteri-latina');

insert into film values ('Spencer', 'Pablo Larrain', 'Drammatico, biografico', '2021', 'USA', '117 min', '24 marzo 2022', '01 Distribution, Leone Film Group', 'Nel 1991, durante le vacanze di Natale con la famiglia reale a Sandringham House, nel Norfolk, Diana Spencer decide di porre fine al suo matrimonio da tempo in crisi con Carlo, principe del Galles.', '../image/locandine/locandina (10).jpg', 'https://www.youtube.com/embed/afbWges06hA', 'sanlorenzo-cerveteri-latina');

insert into film values ('I segreti di Silente', 'David Yates', 'Avventura, Family, Fantasy', '2022', 'USA', '142 min', '13 aprile 2022', 'Warner Bros. Pictures', 'Il professor Albus Silente sa che il potente mago oscuro Gellert Grindelwald si sta muovendo per prendere il controllo del mondo magico. Incapace di fermarlo da solo, incarica il magizoologo Newt Scamander di guidare un intrepida squadra di maghi, streghe e un coraggioso fornaio Babbano in una pericolosa missione. Durante il loro percorso incontreranno animali vecchi e nuovi e si scontreranno con la legione di seguaci di Grindelwald, in costante crescita. Ma con la posta in gioco così alta, per quanto tempo Silente potrà restare in disparte?', '../image/locandine/locandina (11).jpg', 'https://www.youtube.com/embed/i0in1cRXgE8', 'sanlorenzo-cerveteri-latina');

insert into film values ('The Lost City', 'Aaron Nee, Adam Nee', 'Azione, Avventura, Commedia', '2022', 'USA', '112 min', '21 aprile 2022', 'Eagle Pictures', 'Volendo dimostrare che può essere un eroe nella vita reale e non solo sulle pagine dei suoi libri, Alan parte per salvarla. Spinta in un epica avventura nella giungla, l improbabile coppia dovrà lavorare insieme per sopravvivere agli elementi e trovare l antico tesoro prima che sia perso per sempre.', '../image/locandine/locandina (12).jpg', 'https://www.youtube.com/embed/OwbMHEuPEJo', 'sanlorenzo');

insert into film values ('Una vita in fuga', 'Sean Penn', 'Thriller, Drammatico', '2021', 'USA', '107 min', '31 marzo 2022', 'Lucky Red', 'Narra il rapporto irrisolto tra un padre bugiardo e criminale e una figlia che, invece, ha proprio il mito di papà. Almeno fino all età adulta… Dalla storia incredibilmente vera del truffatore John Bryson Vogel, l amore e odio della figlia Jessica per il genitore.', '../image/locandine/locandina (13).jpg', 'https://www.youtube.com/embed/BZnKiAeg9_8', 'cerveteri-latina');

insert into film values ('This much I know to be true', 'Andrew Dominik', 'Documentario', '2022', 'Gran Bretagna', '101 min', '23 maggio 2022', 'Nexo Digital', 'Focus sulla relazione creativa e sulle canzoni dei due ultimi album in studio di Nick Cave e Warren Ellis, "Ghosteen" e "Carnage".', '../image/locandine/locandina (14).jpg', 'https://www.youtube.com/embed/PFPTcbqWoc8', 'sanlorenzo-latina');

insert into film values ('Top gun', 'Joseph Kosinski', 'Azione', '2022', 'USA', '131 min', '25 maggio 2022', 'Eagle Pictures / Paramount Pictures Italia', 'Un pilota di caccia si innamora della propria bionda istruttrice, Charlotte Blackwood, e si crede responsabile della morte del copilota. L esperienza nel programma di formazione lo forza a crescere.', '../image/locandine/locandina (15).jpg', 'https://www.youtube.com/embed/95j_EVjYI_M', 'sanlorenzo-cerveteri-latina');

insert into film values ('Sing', 'Garth Jennings', 'Animazione, Commedia, Musicale', '2016', 'USA', '110 min', '04 gennaio 2017', 'Universal Pictures', 'Buster, un koala proprietario di un teatro ormai caduto in disgrazia, vuole raggiungere il successo partecipando a un importante competizione canora, ma per vincere deve affrontare cinque accaniti concorrenti.', '../image/locandine/locandina (16).jpg', 'https://www.youtube.com/embed/EyGEX74LjVo', 'cerveteri-latina');

insert into film values ('The Northman', 'Robert Eggers', 'Avventura, Drammatico', '2022', 'USA, Gran Bretagna', '140 min', '21 aprile 2022', 'Universal Pictures', 'Il principe Amleth sta per diventare un uomo quando suo padre viene brutalmente assassinato. Due decenni dopo, Amleth, ora un vichingo, incontra una veggente che gli ricorda il suo voto.', '../image/locandine/locandina (17).jpg', 'https://www.youtube.com/embed/ow-L4bFkEV4', 'sanlorenzo-cerveteri-latina');

insert into film values ('Corro da te', 'Riccardo Milani', 'Commedia, Sentimentale', '2022', 'Italia', '113 min', '17 marzo 2022', 'Vision Distribution, Universal Pictures', 'Gianni (interpretato da Pierfrancesco Favino) è un aitante scapolo di 50 anni a cui la vita ha dato tutto, o così sembra: è un uomo sportivo e di successo, è proprietario di un brand di scarpe noto in tutto il mondo ed è in grado di conquistare qualsiasi donna lui desideri.', '../image/locandine/locandina (18).jpg', 'https://www.youtube.com/embed/SHrj60ux5AE', 'sanlorenzo-latina');


