insert into film values ('Uncharted', 'Ruben Fleischer', 'Azione, Avventura', '2022', 'USA', '116 min', '17 febbraio 2022', 'Sony Pictures/ Warner Bros. Italia', 'Basato su una delle serie di videogiochi più vendute e acclamate dalla critica, Uncharted presenta al pubblico il giovane e furbo Nathan Drake (Tom Holland)nella sua prima avventura alla ricerca del tesoro con l’arguto partner Victor “Sully” Sullivan (Mark Wahlberg). In un’epica avventura piena di azione che attraversa il mondo intero, i due protagonisti partono alla pericolosa ricerca del “più grande tesoro mai trovato”, inseguendo indizi che potrebbero condurli al fratello di Nathan, scomparso da tempo.', '../image/locandine/locandina (1).jpg', 'https://www.youtube.com/embed/eHp3MbsCbMg', 'sanlorenzo-cerveteri-latina',2);

insert into film values ('La figlia oscura', 'Maggie Gyllenhaal', 'Drammatico', '2021', 'USA, Gran Bretagna, Israele, Grecia', '121 min', '07 aprile 2022', 'BIM Distribuzione', 'Durante una vacanza al mare da sola, Leda (Olivia Colman) rimane incuriosita e affascinata da una giovane madre (Dakota Johnson) e dalla sua figlioletta mentre le osserva sulla spiaggia. Turbata dal loro irresistibile rapporto, (e dalla loro chiassosa e minacciosa famiglia allargata), Leda è sopraffatta dai suoi stessi ricordi personali dei sentimenti di terrore, confusione e intensità provati nelle prime fasi della maternità. Un gesto impulsivo sconvolge Leda e la proietta nello strano e sinistro mondo della sua stessa mente, dove è costretta ad affrontare le scelte non convenzionali che ha compiuto quando era una giovane madre e le loro conseguenze.', '../image/locandine/locandina (2).jpg', 'https://www.youtube.com/embed/ALtLuqMUOI4', 'latina',4);

insert into film values ('Morbius', 'Daniel Espinosa', 'Fantasy, Azione, Dramma', '2022', 'USA', '108 min', '31 marzo 2022', 'Sony Pictures/ Warner Bros.', 'L’attore Premio Oscar Jared Leto presta il volto al più tormentato antieroe dell’universo Marvel. Il Dr. Morbius è un biologo geniale, tormentato da una rara malattia del sangue. Determinato a trovare una cura, tenta una mossa disperata.', '../image/locandine/locandina (7).jpg', 'https://www.youtube.com/embed/6FxUdXgEeVQ', 'cerveteri',2);

insert into film values ('The Lost City', 'Aaron Nee, Adam Nee', 'Azione, Avventura, Commedia', '2022', 'USA', '112 min', '21 aprile 2022', 'Eagle Pictures', 'Volendo dimostrare che può essere un eroe nella vita reale e non solo sulle pagine dei suoi libri, Alan parte per salvarla. Spinta in un epica avventura nella giungla, l improbabile coppia dovrà lavorare insieme per sopravvivere agli elementi e trovare l antico tesoro prima che sia perso per sempre.', '../image/locandine/locandina (12).jpg', 'https://www.youtube.com/embed/OwbMHEuPEJo', 'sanlorenzo',3);

insert into film values ('Una vita in fuga', 'Sean Penn', 'Thriller, Drammatico', '2021', 'USA', '107 min', '31 marzo 2022', 'Lucky Red', 'Narra il rapporto irrisolto tra un padre bugiardo e criminale e una figlia che, invece, ha proprio il mito di papà. Almeno fino all età adulta… Dalla storia incredibilmente vera del truffatore John Bryson Vogel, l amore e odio della figlia Jessica per il genitore.', '../image/locandine/locandina (13).jpg', 'https://www.youtube.com/embed/BZnKiAeg9_8', 'cerveteri-latina',1);

insert into film values ('I segreti di Silente', 'David Yates', 'Avventura, Family, Fantasy', '2022', 'USA', '142 min', '13 aprile 2022', 'Warner Bros. Pictures', 'Il professor Albus Silente sa che il potente mago oscuro Gellert Grindelwald si sta muovendo per prendere il controllo del mondo magico. Incapace di fermarlo da solo, incarica il magizoologo Newt Scamander di guidare un intrepida squadra di maghi, streghe e un coraggioso fornaio Babbano in una pericolosa missione. Durante il loro percorso incontreranno animali vecchi e nuovi e si scontreranno con la legione di seguaci di Grindelwald, in costante crescita. Ma con la posta in gioco così alta, per quanto tempo Silente potrà restare in disparte?', '../image/locandine/locandina (11).jpg', 'https://www.youtube.com/embed/i0in1cRXgE8', 'sanlorenzo-cerveteri',3);

insert into film values ('The Northman', 'Robert Eggers', 'Avventura, Drammatico', '2022', 'USA, Gran Bretagna', '140 min', '21 aprile 2022', 'Universal Pictures', 'Il principe Amleth sta per diventare un uomo quando suo padre viene brutalmente assassinato. Due decenni dopo, Amleth, ora un vichingo, incontra una veggente che gli ricorda il suo voto.', '../image/locandine/locandina (17).jpg', 'https://www.youtube.com/embed/ow-L4bFkEV4', 'sanlorenzo-latina',3);